# Generated by Django 3.1.6 on 2021-02-04 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=15, null=True)),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
                ('institute1', models.CharField(blank=True, max_length=20, null=True)),
                ('institute2', models.CharField(blank=True, max_length=20, null=True)),
                ('institute3', models.CharField(blank=True, max_length=20, null=True)),
                ('institute4', models.CharField(blank=True, max_length=20, null=True)),
                ('degree1', models.CharField(blank=True, max_length=8, null=True)),
                ('degree2', models.CharField(blank=True, max_length=8, null=True)),
                ('degree3', models.CharField(blank=True, max_length=8, null=True)),
                ('degree4', models.CharField(blank=True, max_length=8, null=True)),
                ('year1', models.CharField(blank=True, max_length=4, null=True)),
                ('year2', models.CharField(blank=True, max_length=4, null=True)),
                ('year3', models.CharField(blank=True, max_length=4, null=True)),
                ('year4', models.CharField(blank=True, max_length=4, null=True)),
                ('grade1', models.CharField(blank=True, max_length=8, null=True)),
                ('grade2', models.CharField(blank=True, max_length=8, null=True)),
                ('grade3', models.CharField(blank=True, max_length=8, null=True)),
                ('grade4', models.CharField(blank=True, max_length=8, null=True)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('certifications', models.CharField(blank=True, max_length=100, null=True)),
                ('companyname1', models.CharField(blank=True, max_length=20, null=True)),
                ('companyname2', models.CharField(blank=True, max_length=20, null=True)),
                ('companyname3', models.CharField(blank=True, max_length=20, null=True)),
                ('position1', models.CharField(blank=True, max_length=20, null=True)),
                ('position2', models.CharField(blank=True, max_length=20, null=True)),
                ('position3', models.CharField(blank=True, max_length=20, null=True)),
                ('duty1', models.CharField(blank=True, max_length=20, null=True)),
                ('duty2', models.CharField(blank=True, max_length=20, null=True)),
                ('duty3', models.CharField(blank=True, max_length=20, null=True)),
                ('timeperiod1', models.CharField(blank=True, max_length=20, null=True)),
                ('timeperiod2', models.CharField(blank=True, max_length=20, null=True)),
                ('timeperiod3', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.CharField(blank=True, max_length=150, null=True)),
                ('interest', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
